
services:

  postgres:
    image: postgres:latest
    container_name: study-platform-postgres
    restart: unless-stopped
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study-platform-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: study-platform-redis
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6000:6379"
    volumes:
      - redis-data:/var/lib/redis/data

  study-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-platform
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:8080"
      - "9443:8443"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/study-platform-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KEYSTORE_PATH: /app/keystore.jks

volumes:
  postgres-data:
  redis-data: