


### Security Requests



###
GET https://localhost:8443/api/v1/security/csrf-token
Accept: application/json

###
GET https://localhost:8443/api/v1/security/login
Accept: text/plain
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET https://localhost:8443/api/v1/security/logout
Accept: text/plain



### Identity Requests



###
POST https://localhost:8443/api/v1/identities/create
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: 0ec80af2-029a-4470-b177-3add1f1fcf56

{
    "authority": "ADMIN",
    "email": "burgasvv@gmail.com",
    "password": "burgasvv",
    "status": true,
    "firstname": "Бургас",
    "lastname": "Вячеслав",
    "patronymic": "Васильевич",
    "about": "Личная информация об аккаунте"
}

###
POST https://localhost:8443/api/v1/identities/create
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: 0ec80af2-029a-4470-b177-3add1f1fcf56

{
    "authority": "USER",
    "email": "zagor@gmail.com",
    "password": "zagor",
    "status": true,
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич",
    "about": "Личная информация об аккаунте Загорулько Бориса Юрьевича"
}

###
POST https://localhost:8443/api/v1/identities/update
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: 0ec80af2-029a-4470-b177-3add1f1fcf56

{
    "id": "e2385462-0674-47c3-96c0-c5666526c76f",
    "about": "Личная информация о пользователе Бургасе Вячеславе Васильевиче"
}

###
POST https://localhost:8443/api/v1/identities/delete?identityId=4035710d-88b0-4a45-a2f8-71949ea0a06e
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc

###
GET https://localhost:8443/api/v1/identities/by-id?identityId=e2385462-0674-47c3-96c0-c5666526c76f
Accept: application/json

###
GET https://localhost:8443/api/v1/identities
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
PUT https://localhost:8443/api/v1/identities/change-password
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc

{
    "id": "abc20e80-0b42-4619-82d1-bf18a7d422f1",
    "password": "burgasvv"
}

###
PUT https://localhost:8443/api/v1/identities/change-status
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "1a224a3a-9538-4e4d-af2e-e737f6246204",
    "status": true
}



### Course Requests



###
POST https://localhost:8443/api/v1/courses/create
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "name": "Java разработчик",
    "description": "Описание курса Java разработчик"
}

###
PUT https://localhost:8443/api/v1/courses/update
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "51b325af-7b99-4f13-a3c3-7aad0a1776df",
    "description": "Описание нового курса Java разработчик"
}

###
DELETE https://localhost:8443/api/v1/courses/delete?courseId=51b325af-7b99-4f13-a3c3-7aad0a1776df
Accept: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET https://localhost:8443/api/v1/courses
Accept: application/json

###
GET https://localhost:8443/api/v1/courses/by-id?courseId=0d518a52-e188-47ca-befd-742ce4786812
Accept: application/json

###
PUT https://localhost:8443/api/v1/courses/add-identity
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc

{
    "courseId": "0d518a52-e188-47ca-befd-742ce4786812",
    "identityId": "abc20e80-0b42-4619-82d1-bf18a7d422f1"
}

###
PUT https://localhost:8443/api/v1/courses/remove-identity
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc

{
    "courseId": "0d518a52-e188-47ca-befd-742ce4786812",
    "identityId": "abc20e80-0b42-4619-82d1-bf18a7d422f1"
}



### Project Requests



###
POST https://localhost:8443/api/v1/projects/create
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "name": "Variables Part",
    "description": "Описание проекта Variables Part",
    "courseId": "0d518a52-e188-47ca-befd-742ce4786812"
}

###
PUT https://localhost:8443/api/v1/projects/update
Accept: application/json
Content-Type: application/json
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "eb91e07e-973e-4ebd-881e-b042419c526e",
    "name": "Variables New Part"
}

###
DELETE https://localhost:8443/api/v1/projects/delete?projectId=eb91e07e-973e-4ebd-881e-b042419c526e
Origin: https://localhost:8443
X-Csrf-Token: cdd80ace-185e-49d2-a18b-15e5286966cc
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET https://localhost:8443/api/v1/projects/by-id?projectId=3e585146-da09-4580-8bd1-95ae4c27f05b
Accept: application/json