
ktor:
  deployment:
    port: 9000
    host: 0.0.0.0
  application:
    modules:
      - org.burgas.security.SecurityKt.configureSecurity
      - org.burgas.serialization.SerializationKt.configureSerialization
      - org.burgas.database.DatabaseKt.configureDatabase
      - org.burgas.routing.SecurityRouterKt.configureSecurityRouter
      - org.burgas.routing.IdentityRouterKt.configureIdentityRouter